/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Material = IDL.Variant({
  'other' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const JobType = IDL.Variant({ 'new' : IDL.Null, 'repair' : IDL.Null });
export const JobId = IDL.Nat;
export const Time = IDL.Int;
export const JobRecord = IDL.Record({
  'id' : JobId,
  'lossWeight' : IDL.Opt(IDL.Float64),
  'jobType' : JobType,
  'date' : IDL.Text,
  'createdAt' : Time,
  'workReceivedDate' : IDL.Opt(IDL.Text),
  'workDescription' : IDL.Opt(IDL.Text),
  'makingChargeKarigar' : IDL.Opt(IDL.Float64),
  'itemName' : IDL.Opt(IDL.Text),
  'makingChargeCustomer' : IDL.Opt(IDL.Float64),
  'otherCharge' : IDL.Opt(IDL.Float64),
  'givenMaterialWeight' : IDL.Opt(IDL.Float64),
  'receivedItemWeight' : IDL.Opt(IDL.Float64),
  'returnScrapWeight' : IDL.Opt(IDL.Float64),
  'remarks' : IDL.Opt(IDL.Text),
  'billNo' : IDL.Text,
  'material' : Material,
});

export const idlService = IDL.Service({
  'createJobRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Material,
        JobType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [JobId],
      [],
    ),
  'deleteJobRecord' : IDL.Func([JobId], [], []),
  'getAllJobRecords' : IDL.Func([], [IDL.Vec(JobRecord)], ['query']),
  'getJobRecord' : IDL.Func([JobId], [JobRecord], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Material = IDL.Variant({
    'other' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const JobType = IDL.Variant({ 'new' : IDL.Null, 'repair' : IDL.Null });
  const JobId = IDL.Nat;
  const Time = IDL.Int;
  const JobRecord = IDL.Record({
    'id' : JobId,
    'lossWeight' : IDL.Opt(IDL.Float64),
    'jobType' : JobType,
    'date' : IDL.Text,
    'createdAt' : Time,
    'workReceivedDate' : IDL.Opt(IDL.Text),
    'workDescription' : IDL.Opt(IDL.Text),
    'makingChargeKarigar' : IDL.Opt(IDL.Float64),
    'itemName' : IDL.Opt(IDL.Text),
    'makingChargeCustomer' : IDL.Opt(IDL.Float64),
    'otherCharge' : IDL.Opt(IDL.Float64),
    'givenMaterialWeight' : IDL.Opt(IDL.Float64),
    'receivedItemWeight' : IDL.Opt(IDL.Float64),
    'returnScrapWeight' : IDL.Opt(IDL.Float64),
    'remarks' : IDL.Opt(IDL.Text),
    'billNo' : IDL.Text,
    'material' : Material,
  });
  
  return IDL.Service({
    'createJobRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Material,
          JobType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [JobId],
        [],
      ),
    'deleteJobRecord' : IDL.Func([JobId], [], []),
    'getAllJobRecords' : IDL.Func([], [IDL.Vec(JobRecord)], ['query']),
    'getJobRecord' : IDL.Func([JobId], [JobRecord], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };