/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type JobId = bigint;
export interface JobRecord {
  'id' : JobId,
  'lossWeight' : [] | [number],
  'jobType' : JobType,
  'date' : string,
  'createdAt' : Time,
  'workReceivedDate' : [] | [string],
  'workDescription' : [] | [string],
  'makingChargeKarigar' : [] | [number],
  'itemName' : [] | [string],
  'makingChargeCustomer' : [] | [number],
  'otherCharge' : [] | [number],
  'givenMaterialWeight' : [] | [number],
  'receivedItemWeight' : [] | [number],
  'returnScrapWeight' : [] | [number],
  'remarks' : [] | [string],
  'billNo' : string,
  'material' : Material,
}
export type JobType = { 'new' : null } |
  { 'repair' : null };
export type Material = { 'other' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export type Time = bigint;
export interface _SERVICE {
  'createJobRecord' : ActorMethod<
    [
      string,
      string,
      Material,
      JobType,
      [] | [string],
      [] | [number],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
      [] | [string],
    ],
    JobId
  >,
  'deleteJobRecord' : ActorMethod<[JobId], undefined>,
  'getAllJobRecords' : ActorMethod<[], Array<JobRecord>>,
  'getJobRecord' : ActorMethod<[JobId], JobRecord>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];