/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type JobId = bigint;
export type Time = bigint;
export interface JobRecord {
    id: JobId;
    lossWeight?: number;
    jobType: JobType;
    date: string;
    createdAt: Time;
    workReceivedDate?: string;
    workDescription?: string;
    makingChargeKarigar?: number;
    itemName?: string;
    makingChargeCustomer?: number;
    otherCharge?: number;
    givenMaterialWeight?: number;
    receivedItemWeight?: number;
    returnScrapWeight?: number;
    remarks?: string;
    billNo: string;
    material: Material;
}
export enum JobType {
    new_ = "new",
    repair = "repair"
}
export enum Material {
    other = "other",
    gold = "gold",
    silver = "silver"
}
export interface backendInterface {
    createJobRecord(date: string, billNo: string, material: Material, jobType: JobType, itemName: string | null, givenMaterialWeight: number | null, workReceivedDate: string | null, receivedItemWeight: number | null, returnScrapWeight: number | null, lossWeight: number | null, otherCharge: number | null, makingChargeCustomer: number | null, makingChargeKarigar: number | null, workDescription: string | null, remarks: string | null): Promise<JobId>;
    deleteJobRecord(jobId: JobId): Promise<void>;
    getAllJobRecords(): Promise<Array<JobRecord>>;
    getJobRecord(jobId: JobId): Promise<JobRecord>;
}
import type { JobId as _JobId, JobRecord as _JobRecord, JobType as _JobType, Material as _Material, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createJobRecord(arg0: string, arg1: string, arg2: Material, arg3: JobType, arg4: string | null, arg5: number | null, arg6: string | null, arg7: number | null, arg8: number | null, arg9: number | null, arg10: number | null, arg11: number | null, arg12: number | null, arg13: string | null, arg14: string | null): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobRecord(arg0, arg1, to_candid_Material_n1(this._uploadFile, this._downloadFile, arg2), to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg14));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobRecord(arg0, arg1, to_candid_Material_n1(this._uploadFile, this._downloadFile, arg2), to_candid_JobType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg14));
            return result;
        }
    }
    async deleteJobRecord(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobRecord(arg0);
            return result;
        }
    }
    async getAllJobRecords(): Promise<Array<JobRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobRecords();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobRecords();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobRecord(arg0: JobId): Promise<JobRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobRecord(arg0);
                return from_candid_JobRecord_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobRecord(arg0);
            return from_candid_JobRecord_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_JobRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRecord): JobRecord {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Material_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Material {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    lossWeight: [] | [number];
    jobType: _JobType;
    date: string;
    createdAt: _Time;
    workReceivedDate: [] | [string];
    workDescription: [] | [string];
    makingChargeKarigar: [] | [number];
    itemName: [] | [string];
    makingChargeCustomer: [] | [number];
    otherCharge: [] | [number];
    givenMaterialWeight: [] | [number];
    receivedItemWeight: [] | [number];
    returnScrapWeight: [] | [number];
    remarks: [] | [string];
    billNo: string;
    material: _Material;
}): {
    id: JobId;
    lossWeight?: number;
    jobType: JobType;
    date: string;
    createdAt: Time;
    workReceivedDate?: string;
    workDescription?: string;
    makingChargeKarigar?: number;
    itemName?: string;
    makingChargeCustomer?: number;
    otherCharge?: number;
    givenMaterialWeight?: number;
    receivedItemWeight?: number;
    returnScrapWeight?: number;
    remarks?: string;
    billNo: string;
    material: Material;
} {
    return {
        id: value.id,
        lossWeight: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lossWeight)),
        jobType: from_candid_JobType_n11(_uploadFile, _downloadFile, value.jobType),
        date: value.date,
        createdAt: value.createdAt,
        workReceivedDate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.workReceivedDate)),
        workDescription: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.workDescription)),
        makingChargeKarigar: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.makingChargeKarigar)),
        itemName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.itemName)),
        makingChargeCustomer: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.makingChargeCustomer)),
        otherCharge: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.otherCharge)),
        givenMaterialWeight: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.givenMaterialWeight)),
        receivedItemWeight: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.receivedItemWeight)),
        returnScrapWeight: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.returnScrapWeight)),
        remarks: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.remarks)),
        billNo: value.billNo,
        material: from_candid_Material_n14(_uploadFile, _downloadFile, value.material)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    repair: null;
}): JobType {
    return "new" in value ? JobType.new : "repair" in value ? JobType.repair : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    gold: null;
} | {
    silver: null;
}): Material {
    return "other" in value ? Material.other : "gold" in value ? Material.gold : "silver" in value ? Material.silver : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobRecord>): Array<JobRecord> {
    return value.map((x)=>from_candid_JobRecord_n8(_uploadFile, _downloadFile, x));
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Material_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Material): _Material {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Material): {
    other: null;
} | {
    gold: null;
} | {
    silver: null;
} {
    return value == Material.other ? {
        other: null
    } : value == Material.gold ? {
        gold: null
    } : value == Material.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    new: null;
} | {
    repair: null;
} {
    return value == JobType.new ? {
        new_: null
    } : value == JobType.repair ? {
        repair: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
